#!/usr/bin/env python3
"""Translate catalog/policies.yaml into concrete scanner settings.

Consumed by the promote job in publish-approved-image.yml (A2). The workflow
keeps catalog/policies.yaml as the single source of truth for scanner
thresholds and CVE exceptions; this script reads that declarative policy and
emits the concrete knobs each scanner consumes:

  * Snyk:  a single ``--severity-threshold`` floor (the lowest blocking
    severity).
  * Trivy: a comma-separated ``severity`` list of blocking severities, plus a
    generated ``.trivyignore`` of non-expired CVE exceptions for the image.
  * Cosign: the ``required`` flag and the certificate identity / issuer
    regexps used to verify the upstream signature.

Outputs are written as ``key=value`` lines to the file named by
``--github-output`` (default: the ``GITHUB_OUTPUT`` environment variable) so a
later workflow step can reference them via ``steps.<id>.outputs.<key>``.

Expiry handling is fail-safe: an exception whose ``expires`` date is in the
past, missing, or unparseable does NOT suppress its finding, so the scanner
gate still blocks. A sloppy policy file therefore fails closed, never open.

Exit codes:
  0  Policy loaded and outputs written.
  1  Argument error, missing/invalid policy file, or malformed policy.
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import date, datetime, timezone
from pathlib import Path

import yaml

# Severity ranking, lowest to highest. Used to pick the Snyk threshold floor
# and to order the Trivy severity list deterministically.
_SEVERITY_ORDER = ["low", "medium", "high", "critical"]
_BLOCK = "block"
_VALID_SCANNERS = {"snyk", "trivy", "both"}


def _fail(message: str) -> int:
    print(f"ERROR: {message}", file=sys.stderr)
    return 1


def _blocking_severities(scanner_cfg: dict[str, str]) -> list[str]:
    """Return severities whose action is ``block``, lowest-first."""
    blocking = [
        sev
        for sev in _SEVERITY_ORDER
        if str(scanner_cfg.get(sev, "")).lower() == _BLOCK
    ]
    return blocking


def _snyk_threshold(snyk_cfg: dict[str, str]) -> str:
    """Lowest blocking severity is the Snyk ``--severity-threshold`` floor.

    Snyk fails the scan on any finding at or above the floor, so the floor is
    the least-severe level the policy marks ``block``. If nothing blocks, fall
    back to ``critical`` (the most permissive floor that still scans).
    """
    blocking = _blocking_severities(snyk_cfg)
    return blocking[0] if blocking else "critical"


def _trivy_severities(trivy_cfg: dict[str, str]) -> str:
    """Comma-separated uppercase list of blocking severities, highest-first."""
    blocking = _blocking_severities(trivy_cfg)
    return ",".join(sev.upper() for sev in reversed(blocking))


def _parse_expiry(value: object) -> date | None:
    """Parse an ISO-8601 ``YYYY-MM-DD`` date, or None if unparseable."""
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if not isinstance(value, str):
        return None
    try:
        return date.fromisoformat(value.strip())
    except ValueError:
        return None


def _active_exceptions(
    exceptions: list[dict[str, object]],
    image_id: str,
    today: date,
) -> tuple[list[str], list[str], list[str]]:
    """Split non-expired exceptions for ``image_id`` by scanner.

    Returns ``(trivy_cves, snyk_cves, skipped)`` where ``skipped`` records
    entries dropped because they expired or had an invalid ``expires`` date.
    Fail-safe: a dropped exception does not suppress its finding.
    """
    trivy_cves: list[str] = []
    snyk_cves: list[str] = []
    skipped: list[str] = []
    for entry in exceptions:
        if not isinstance(entry, dict):
            continue
        if entry.get("image_id") != image_id:
            continue
        cve = str(entry.get("cve_id", "")).strip()
        if not cve:
            continue
        expiry = _parse_expiry(entry.get("expires"))
        if expiry is None or expiry < today:
            reason = "invalid expires" if expiry is None else "expired"
            skipped.append(f"{cve} ({reason})")
            continue
        scanner = str(entry.get("scanner", "")).lower()
        if scanner not in _VALID_SCANNERS:
            skipped.append(f"{cve} (invalid scanner '{scanner}')")
            continue
        if scanner in ("trivy", "both"):
            trivy_cves.append(cve)
        if scanner in ("snyk", "both"):
            snyk_cves.append(cve)
    return trivy_cves, snyk_cves, skipped


def _write_trivyignore(path: Path, cves: list[str], image_id: str) -> None:
    """Write a .trivyignore file listing one approved CVE per line."""
    lines = [
        "# Generated by scripts/load_scanner_policy.py from catalog/policies.yaml.",
        f"# Active, non-expired exceptions for image: {image_id}.",
        "# Do not edit by hand; edit catalog/policies.yaml instead.",
    ]
    lines.extend(cves)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _emit_outputs(output_path: Path, outputs: dict[str, str]) -> None:
    """Append key=value output lines for a later workflow step to read."""
    with output_path.open("a", encoding="utf-8") as fh:
        for key, value in outputs.items():
            fh.write(f"{key}={value}\n")


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Translate catalog/policies.yaml into scanner settings"
    )
    p.add_argument("--policy-file", required=True, help="Path to catalog/policies.yaml")
    p.add_argument("--image-id", required=True, help="Catalog image id being promoted")
    p.add_argument(
        "--trivyignore-out",
        default=".trivyignore",
        help="Path to write the generated .trivyignore",
    )
    p.add_argument(
        "--github-output",
        default=os.environ.get("GITHUB_OUTPUT", ""),
        help="Path to append key=value outputs (default: $GITHUB_OUTPUT)",
    )
    p.add_argument(
        "--today",
        default=None,
        help="Override today's date (YYYY-MM-DD) for deterministic tests",
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()

    policy_path = Path(args.policy_file)
    if not policy_path.is_file():
        return _fail(f"policy file not found: {policy_path}")

    try:
        with policy_path.open(encoding="utf-8") as fh:
            policy = yaml.safe_load(fh)
    except yaml.YAMLError as exc:
        return _fail(f"policy file is not valid YAML: {exc}")

    if not isinstance(policy, dict):
        return _fail("policy file is not a YAML mapping")

    scanner_policy = policy.get("scanner_policy")
    if not isinstance(scanner_policy, dict):
        return _fail("policy file is missing a 'scanner_policy' mapping")

    snyk_cfg = scanner_policy.get("snyk") or {}
    trivy_cfg = scanner_policy.get("trivy") or {}
    cosign_cfg = scanner_policy.get("upstream_cosign") or {}

    if args.today:
        today = _parse_expiry(args.today)
        if today is None:
            return _fail(f"invalid --today value: {args.today}")
    else:
        today = datetime.now(timezone.utc).date()

    exceptions = policy.get("exceptions") or []
    if not isinstance(exceptions, list):
        return _fail("'exceptions' must be a list")

    trivy_cves, snyk_cves, skipped = _active_exceptions(
        exceptions, args.image_id, today
    )

    trivyignore_path = Path(args.trivyignore_out)
    _write_trivyignore(trivyignore_path, trivy_cves, args.image_id)

    identity = str(cosign_cfg.get("expected_identity_regexp", ".*"))
    issuer = str(cosign_cfg.get("expected_issuer_regexp", ".*"))

    outputs = {
        "snyk_threshold": _snyk_threshold(snyk_cfg),
        "trivy_severities": _trivy_severities(trivy_cfg),
        "trivyignore_file": str(trivyignore_path),
        "trivy_exception_count": str(len(trivy_cves)),
        "snyk_exception_cves": ",".join(snyk_cves),
        "cosign_required": "true" if cosign_cfg.get("required") else "false",
        "cosign_identity_regexp": identity,
        "cosign_issuer_regexp": issuer,
        "cosign_identity_pinned": "false" if identity == ".*" else "true",
    }

    # Human-readable trace in the job log (stdout, not an output channel).
    print(f"Scanner policy for {args.image_id}:")
    for key, value in outputs.items():
        print(f"  {key}={value}")
    if skipped:
        print(f"  skipped exceptions (fail-safe, still blocking): {skipped}")

    if args.github_output:
        _emit_outputs(Path(args.github_output), outputs)

    return 0


if __name__ == "__main__":
    sys.exit(main())
